import os
import subprocess
import shutil
from pathlib import Path
from config import Config

class PDFParser:
    def __init__(self):
        self.output_dir = Path(Config.OUTPUT_DIR)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def parse(self, pdf_path: str) -> str:
        """
        Parse PDF to Markdown using magic-pdf.
        Returns the path to the generated Markdown file.
        """
        pdf_path = Path(pdf_path)
        if not pdf_path.exists():
            raise FileNotFoundError(f"PDF file not found: {pdf_path}")

        print(f"Parsing PDF: {pdf_path}...")
        
        # Create a specific output subdirectory for this file
        file_stem = pdf_path.stem
        file_output_dir = self.output_dir / file_stem
        
        # Clean up previous run if exists
        if file_output_dir.exists():
            shutil.rmtree(file_output_dir)
        file_output_dir.mkdir(parents=True, exist_ok=True)

        # Run magic-pdf via CLI
        # Command: magic-pdf -p {pdf_path} -o {output_dir} -m auto
        cmd = [
            "magic-pdf",
            "-p", str(pdf_path),
            "-o", str(self.output_dir), # magic-pdf creates a subdir with the file name inside this
            "-m", "auto"
        ]
        
        try:
            result = subprocess.run(cmd, check=True, capture_output=True, text=True)
            print(result.stdout)
        except subprocess.CalledProcessError as e:
            print(f"Error running magic-pdf: {e.stderr}")
            raise RuntimeError("PDF parsing failed.")

        # Locate the generated markdown file
        # magic-pdf usually creates {output_dir}/{file_stem}/auto/{file_stem}.md or similar
        # Let's search for the .md file
        md_files = list(file_output_dir.rglob("*.md"))
        if not md_files:
            raise FileNotFoundError("Markdown file not generated by magic-pdf.")
        
        # Return the first found markdown file (usually the main one)
        return str(md_files[0])

if __name__ == "__main__":
    # Test
    import sys
    if len(sys.argv) > 1:
        parser = PDFParser()
        print(parser.parse(sys.argv[1]))
